"""Seed universe and source configuration for the isolated demo build.

The symbols are real UAE-market names, but all prices, scores, events, and
financial values emitted by this isolated build are demo data unless a future
provider explicitly replaces the mock adapter.
"""

SECURITIES = [
    {
        "symbol": "FAB",
        "isin": "AE0004901111",
        "name_en": "First Abu Dhabi Bank",
        "name_ar": "بنك أبوظبي الأول",
        "exchange": "ADX",
        "sector": "Banks",
        "archetype": "bank",
        "currency": "AED",
        "price": 15.42,
        "change_pct": 0.8,
        "dividend_yield": 5.1,
        "market_cap_bn": 170.4,
        "volume_m": 12.4,
        "index_membership": ["FADGI", "FTSE ADX 15"],
        "summary": "Largest UAE bank by assets with broad wholesale, retail, and international exposure.",
        "exposures": ["rates", "credit", "usd", "oil-liquidity"],
        "fundamentals": {
            "revenue_growth": 7.0,
            "profit_growth": 10.0,
            "margin_trend": 6.5,
            "capital_allocation": 7.0,
            "strategic_expansion": 6.0,
            "event_catalysts": 6.5,
            "leverage": 7.0,
            "liquidity": 8.5,
            "cashflow_consistency": 8.0,
            "volatility": 6.0,
            "governance_cadence": 8.0,
            "disclosure_consistency": 8.0,
            "macro_sensitivity": 5.0,
            "payout_ratio": 50.0,
            "fcf_coverage": 7.0,
            "debt_burden": 5.0,
            "cut_history": 8.0,
            "frequency": 6.0,
            "regularity": 8.0,
        },
    },
    {
        "symbol": "IHC",
        "isin": "AEI000201014",
        "name_en": "International Holding Company",
        "name_ar": "الشركة العالمية القابضة",
        "exchange": "ADX",
        "sector": "Investment Holding",
        "archetype": "holding",
        "currency": "AED",
        "price": 412.80,
        "change_pct": -0.2,
        "dividend_yield": 0.0,
        "market_cap_bn": 900.0,
        "volume_m": 0.9,
        "index_membership": ["FADGI", "FTSE ADX 15"],
        "summary": "Diversified holding company with exposure across healthcare, food, industry, and technology.",
        "exposures": ["rates", "private-assets", "healthcare", "food-inputs"],
        "fundamentals": {
            "revenue_growth": 12.0,
            "profit_growth": 8.0,
            "margin_trend": 5.5,
            "capital_allocation": 6.0,
            "strategic_expansion": 8.5,
            "event_catalysts": 8.0,
            "leverage": 5.5,
            "liquidity": 6.0,
            "cashflow_consistency": 5.0,
            "volatility": 5.0,
            "governance_cadence": 6.0,
            "disclosure_consistency": 5.5,
            "macro_sensitivity": 7.0,
            "payout_ratio": 0.0,
            "fcf_coverage": 4.5,
            "debt_burden": 5.0,
            "cut_history": 5.0,
            "frequency": 0.0,
            "regularity": 4.0,
        },
    },
    {
        "symbol": "ALDAR",
        "isin": "AEA002001013",
        "name_en": "Aldar Properties",
        "name_ar": "الدار العقارية",
        "exchange": "ADX",
        "sector": "Real Estate",
        "archetype": "developer",
        "currency": "AED",
        "price": 8.76,
        "change_pct": 1.4,
        "dividend_yield": 2.6,
        "market_cap_bn": 68.9,
        "volume_m": 18.0,
        "index_membership": ["FADGI"],
        "summary": "Abu Dhabi developer and asset manager with recurring income and development exposure.",
        "exposures": ["rates", "tourism", "steel", "population-growth"],
        "fundamentals": {
            "revenue_growth": 18.0,
            "profit_growth": 14.0,
            "margin_trend": 7.0,
            "capital_allocation": 7.5,
            "strategic_expansion": 8.0,
            "event_catalysts": 7.5,
            "leverage": 6.5,
            "liquidity": 7.0,
            "cashflow_consistency": 6.5,
            "volatility": 5.5,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.5,
            "macro_sensitivity": 7.0,
            "payout_ratio": 34.0,
            "fcf_coverage": 6.0,
            "debt_burden": 5.5,
            "cut_history": 7.0,
            "frequency": 6.0,
            "regularity": 7.0,
        },
    },
    {
        "symbol": "ADNOCGAS",
        "isin": "AEE01195A234",
        "name_en": "ADNOC Gas",
        "name_ar": "أدنوك للغاز",
        "exchange": "ADX",
        "sector": "Energy",
        "archetype": "energy",
        "currency": "AED",
        "price": 3.52,
        "change_pct": 0.4,
        "dividend_yield": 4.7,
        "market_cap_bn": 270.0,
        "volume_m": 22.5,
        "index_membership": ["FADGI"],
        "summary": "Integrated gas processing company linked to LNG, industrial demand, and energy spreads.",
        "exposures": ["gas", "oil", "lng", "usd"],
        "fundamentals": {
            "revenue_growth": 5.0,
            "profit_growth": 6.0,
            "margin_trend": 6.5,
            "capital_allocation": 6.5,
            "strategic_expansion": 7.0,
            "event_catalysts": 6.5,
            "leverage": 7.0,
            "liquidity": 7.5,
            "cashflow_consistency": 8.0,
            "volatility": 5.0,
            "governance_cadence": 7.5,
            "disclosure_consistency": 7.0,
            "macro_sensitivity": 7.0,
            "payout_ratio": 62.0,
            "fcf_coverage": 7.5,
            "debt_burden": 6.5,
            "cut_history": 7.0,
            "frequency": 8.0,
            "regularity": 8.0,
        },
    },
    {
        "symbol": "TAQA",
        "isin": "AEA002401015",
        "name_en": "Abu Dhabi National Energy Company",
        "name_ar": "شركة أبوظبي الوطنية للطاقة",
        "exchange": "ADX",
        "sector": "Utilities",
        "archetype": "utility",
        "currency": "AED",
        "price": 3.17,
        "change_pct": -0.5,
        "dividend_yield": 3.9,
        "market_cap_bn": 356.0,
        "volume_m": 6.2,
        "index_membership": ["FADGI"],
        "summary": "Power and water utility with regulated cash flows plus energy transition exposure.",
        "exposures": ["rates", "gas", "power-demand", "desalination"],
        "fundamentals": {
            "revenue_growth": 4.0,
            "profit_growth": 3.0,
            "margin_trend": 5.5,
            "capital_allocation": 6.0,
            "strategic_expansion": 6.5,
            "event_catalysts": 5.5,
            "leverage": 5.5,
            "liquidity": 6.5,
            "cashflow_consistency": 8.5,
            "volatility": 7.0,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.0,
            "macro_sensitivity": 4.5,
            "payout_ratio": 70.0,
            "fcf_coverage": 6.5,
            "debt_burden": 5.0,
            "cut_history": 7.0,
            "frequency": 8.0,
            "regularity": 8.0,
        },
    },
    {
        "symbol": "ADPORTS",
        "isin": "AEA007301012",
        "name_en": "AD Ports Group",
        "name_ar": "مجموعة موانئ أبوظبي",
        "exchange": "ADX",
        "sector": "Logistics",
        "archetype": "logistics",
        "currency": "AED",
        "price": 6.10,
        "change_pct": 1.1,
        "dividend_yield": 0.0,
        "market_cap_bn": 31.0,
        "volume_m": 2.7,
        "index_membership": ["FADGI"],
        "summary": "Ports, maritime, logistics, and economic-cities operator tied to regional trade flows.",
        "exposures": ["freight", "trade", "fuel", "usd"],
        "fundamentals": {
            "revenue_growth": 24.0,
            "profit_growth": 13.0,
            "margin_trend": 6.0,
            "capital_allocation": 7.5,
            "strategic_expansion": 8.5,
            "event_catalysts": 8.0,
            "leverage": 5.0,
            "liquidity": 6.0,
            "cashflow_consistency": 6.0,
            "volatility": 5.5,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.5,
            "macro_sensitivity": 7.5,
            "payout_ratio": 0.0,
            "fcf_coverage": 4.5,
            "debt_burden": 4.5,
            "cut_history": 5.0,
            "frequency": 0.0,
            "regularity": 4.0,
        },
    },
    {
        "symbol": "EMAAR",
        "isin": "AEE000301011",
        "name_en": "Emaar Properties",
        "name_ar": "إعمار العقارية",
        "exchange": "DFM",
        "sector": "Real Estate",
        "archetype": "developer",
        "currency": "AED",
        "price": 13.65,
        "change_pct": 1.7,
        "dividend_yield": 6.2,
        "market_cap_bn": 121.3,
        "volume_m": 35.6,
        "index_membership": ["DFMGI"],
        "summary": "Dubai developer with residential, malls, hospitality, and tourism-driven earnings exposure.",
        "exposures": ["rates", "tourism", "population-growth", "steel"],
        "fundamentals": {
            "revenue_growth": 21.0,
            "profit_growth": 18.0,
            "margin_trend": 7.5,
            "capital_allocation": 7.0,
            "strategic_expansion": 8.0,
            "event_catalysts": 8.0,
            "leverage": 7.0,
            "liquidity": 7.0,
            "cashflow_consistency": 7.5,
            "volatility": 5.0,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.0,
            "macro_sensitivity": 7.0,
            "payout_ratio": 58.0,
            "fcf_coverage": 7.0,
            "debt_burden": 6.5,
            "cut_history": 6.5,
            "frequency": 6.0,
            "regularity": 7.0,
        },
    },
    {
        "symbol": "DEWA",
        "isin": "AED001801011",
        "name_en": "Dubai Electricity and Water Authority",
        "name_ar": "هيئة كهرباء ومياه دبي",
        "exchange": "DFM",
        "sector": "Utilities",
        "archetype": "utility",
        "currency": "AED",
        "price": 2.79,
        "change_pct": 0.1,
        "dividend_yield": 6.0,
        "market_cap_bn": 139.5,
        "volume_m": 28.0,
        "index_membership": ["DFMGI"],
        "summary": "Dubai utility with regulated electricity, water, district cooling, and transition assets.",
        "exposures": ["gas", "power-demand", "rates", "population-growth"],
        "fundamentals": {
            "revenue_growth": 5.0,
            "profit_growth": 4.0,
            "margin_trend": 6.5,
            "capital_allocation": 6.5,
            "strategic_expansion": 6.0,
            "event_catalysts": 5.0,
            "leverage": 7.0,
            "liquidity": 7.0,
            "cashflow_consistency": 8.5,
            "volatility": 7.5,
            "governance_cadence": 7.5,
            "disclosure_consistency": 8.0,
            "macro_sensitivity": 4.0,
            "payout_ratio": 80.0,
            "fcf_coverage": 7.0,
            "debt_burden": 6.5,
            "cut_history": 8.0,
            "frequency": 8.0,
            "regularity": 8.0,
        },
    },
    {
        "symbol": "ENBD",
        "isin": "AEE000801010",
        "name_en": "Emirates NBD",
        "name_ar": "الإمارات دبي الوطني",
        "exchange": "DFM",
        "sector": "Banks",
        "archetype": "bank",
        "currency": "AED",
        "price": 23.15,
        "change_pct": 0.6,
        "dividend_yield": 5.3,
        "market_cap_bn": 146.2,
        "volume_m": 4.6,
        "index_membership": ["DFMGI"],
        "summary": "Dubai banking group with retail, corporate, Islamic, and regional international operations.",
        "exposures": ["rates", "credit", "usd", "tourism"],
        "fundamentals": {
            "revenue_growth": 8.0,
            "profit_growth": 11.0,
            "margin_trend": 6.5,
            "capital_allocation": 7.0,
            "strategic_expansion": 6.5,
            "event_catalysts": 6.0,
            "leverage": 7.0,
            "liquidity": 8.0,
            "cashflow_consistency": 8.0,
            "volatility": 6.0,
            "governance_cadence": 8.0,
            "disclosure_consistency": 8.0,
            "macro_sensitivity": 5.0,
            "payout_ratio": 55.0,
            "fcf_coverage": 7.0,
            "debt_burden": 6.5,
            "cut_history": 8.0,
            "frequency": 6.0,
            "regularity": 8.0,
        },
    },
    {
        "symbol": "DIB",
        "isin": "AED000201015",
        "name_en": "Dubai Islamic Bank",
        "name_ar": "بنك دبي الإسلامي",
        "exchange": "DFM",
        "sector": "Banks",
        "archetype": "bank",
        "currency": "AED",
        "price": 7.34,
        "change_pct": -0.1,
        "dividend_yield": 6.4,
        "market_cap_bn": 53.0,
        "volume_m": 10.3,
        "index_membership": ["DFMGI"],
        "summary": "Islamic bank with corporate, retail, and sukuk-market sensitivity.",
        "exposures": ["rates", "credit", "sukuk", "real-estate"],
        "fundamentals": {
            "revenue_growth": 6.0,
            "profit_growth": 9.0,
            "margin_trend": 6.0,
            "capital_allocation": 6.5,
            "strategic_expansion": 5.5,
            "event_catalysts": 5.5,
            "leverage": 6.5,
            "liquidity": 7.5,
            "cashflow_consistency": 8.0,
            "volatility": 6.0,
            "governance_cadence": 7.5,
            "disclosure_consistency": 7.5,
            "macro_sensitivity": 5.0,
            "payout_ratio": 60.0,
            "fcf_coverage": 7.0,
            "debt_burden": 6.0,
            "cut_history": 7.5,
            "frequency": 6.0,
            "regularity": 7.5,
        },
    },
    {
        "symbol": "SALIK",
        "isin": "AEE01110S227",
        "name_en": "Salik Company",
        "name_ar": "سالك",
        "exchange": "DFM",
        "sector": "Transport",
        "archetype": "infrastructure",
        "currency": "AED",
        "price": 5.98,
        "change_pct": 1.0,
        "dividend_yield": 5.7,
        "market_cap_bn": 44.8,
        "volume_m": 9.4,
        "index_membership": ["DFMGI"],
        "summary": "Dubai toll-road operator linked to population, tourism, congestion, and mobility demand.",
        "exposures": ["population-growth", "tourism", "fuel", "rates"],
        "fundamentals": {
            "revenue_growth": 9.0,
            "profit_growth": 10.0,
            "margin_trend": 8.0,
            "capital_allocation": 6.5,
            "strategic_expansion": 6.5,
            "event_catalysts": 7.0,
            "leverage": 6.5,
            "liquidity": 7.0,
            "cashflow_consistency": 8.5,
            "volatility": 7.0,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.5,
            "macro_sensitivity": 4.5,
            "payout_ratio": 85.0,
            "fcf_coverage": 8.0,
            "debt_burden": 6.0,
            "cut_history": 7.0,
            "frequency": 8.0,
            "regularity": 8.0,
        },
    },
    {
        "symbol": "AIRARABIA",
        "isin": "AEA003001012",
        "name_en": "Air Arabia",
        "name_ar": "العربية للطيران",
        "exchange": "DFM",
        "sector": "Aviation",
        "archetype": "cyclical",
        "currency": "AED",
        "price": 3.48,
        "change_pct": -0.7,
        "dividend_yield": 5.0,
        "market_cap_bn": 16.2,
        "volume_m": 8.5,
        "index_membership": ["DFMGI"],
        "summary": "Low-cost carrier exposed to passenger demand, fuel prices, fleet growth, and tourism flows.",
        "exposures": ["oil", "tourism", "usd", "freight"],
        "fundamentals": {
            "revenue_growth": 10.0,
            "profit_growth": 8.0,
            "margin_trend": 5.5,
            "capital_allocation": 6.0,
            "strategic_expansion": 7.0,
            "event_catalysts": 6.0,
            "leverage": 6.5,
            "liquidity": 7.0,
            "cashflow_consistency": 6.5,
            "volatility": 4.5,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.0,
            "macro_sensitivity": 8.0,
            "payout_ratio": 55.0,
            "fcf_coverage": 6.5,
            "debt_burden": 6.0,
            "cut_history": 6.0,
            "frequency": 6.0,
            "regularity": 6.5,
        },
    },
    {
        "symbol": "AMERICANA",
        "isin": "AEE01135A222",
        "name_en": "Americana Restaurants",
        "name_ar": "أمريكانا للمطاعم",
        "exchange": "ADX",
        "sector": "Consumer",
        "archetype": "consumer",
        "currency": "AED",
        "price": 2.41,
        "change_pct": -1.1,
        "dividend_yield": 3.2,
        "market_cap_bn": 20.3,
        "volume_m": 14.7,
        "index_membership": ["FADGI"],
        "summary": "Quick-service restaurant operator exposed to consumer demand, food inputs, and regional expansion.",
        "exposures": ["food-inputs", "usd", "population-growth", "tourism"],
        "fundamentals": {
            "revenue_growth": -3.0,
            "profit_growth": -8.0,
            "margin_trend": 4.0,
            "capital_allocation": 5.0,
            "strategic_expansion": 5.5,
            "event_catalysts": 4.5,
            "leverage": 7.0,
            "liquidity": 7.0,
            "cashflow_consistency": 6.5,
            "volatility": 5.0,
            "governance_cadence": 7.0,
            "disclosure_consistency": 7.0,
            "macro_sensitivity": 7.0,
            "payout_ratio": 65.0,
            "fcf_coverage": 6.0,
            "debt_burden": 6.5,
            "cut_history": 6.0,
            "frequency": 6.0,
            "regularity": 6.5,
        },
    },
]


SOURCE_PROVIDERS = [
    {
        "id": "adx-official",
        "name": "ADX official pages",
        "layer": "official_exchange",
        "status": "adapter_ready",
        "cadence": "2-5 minutes when approved",
        "rights_posture": "Use official links and licensed/public-delayed data only.",
    },
    {
        "id": "dfm-official",
        "name": "DFM official pages",
        "layer": "official_exchange",
        "status": "adapter_ready",
        "cadence": "2-5 minutes when approved",
        "rights_posture": "Arabic is official; English translations are informational.",
    },
    {
        "id": "issuer-ir",
        "name": "Issuer investor relations",
        "layer": "issuer_ir",
        "status": "mocked",
        "cadence": "Daily plus event-triggered refresh",
        "rights_posture": "Index source links and extracted facts with source evidence.",
    },
    {
        "id": "worldbank-commodities",
        "name": "World Bank commodities",
        "layer": "global_signals",
        "status": "mocked",
        "cadence": "15-30 minutes for macro checks",
        "rights_posture": "Use public commodity series with attribution.",
    },
    {
        "id": "gdelt-events",
        "name": "GDELT events",
        "layer": "global_signals",
        "status": "mocked",
        "cadence": "15 minutes",
        "rights_posture": "Use event metadata and source URLs; cluster rather than copy articles.",
    },
]


EXPOSURE_DEFINITIONS = {
    "rates": {
        "label": "Rates",
        "move": "+12 bps",
        "impact": "Higher rates pressure developers and support bank margins until credit costs rise.",
        "sentiment": "mixed",
    },
    "credit": {
        "label": "Credit",
        "move": "Stable spreads",
        "impact": "Stable credit conditions support bank asset quality.",
        "sentiment": "positive",
    },
    "usd": {
        "label": "USD",
        "move": "Firm",
        "impact": "A firm dollar affects imported inputs and regional purchasing power.",
        "sentiment": "neutral",
    },
    "oil": {
        "label": "Oil",
        "move": "+1.8%",
        "impact": "Oil strength supports regional liquidity but can lift fuel-sensitive costs.",
        "sentiment": "mixed",
    },
    "oil-liquidity": {
        "label": "Oil Liquidity",
        "move": "Supportive",
        "impact": "Firm oil can support regional liquidity, deposits, and investor appetite.",
        "sentiment": "positive",
    },
    "fuel": {
        "label": "Fuel",
        "move": "+1.2%",
        "impact": "Fuel costs matter for airlines, logistics, and road-traffic economics.",
        "sentiment": "mixed",
    },
    "gas": {
        "label": "Gas",
        "move": "+0.9%",
        "impact": "Gas-linked revenue and generation costs move in opposite directions by sector.",
        "sentiment": "mixed",
    },
    "lng": {
        "label": "LNG",
        "move": "Asia spot steady",
        "impact": "Steady LNG demand supports gas processing visibility.",
        "sentiment": "positive",
    },
    "steel": {
        "label": "Steel",
        "move": "-0.6%",
        "impact": "Lower steel input costs can help contractors and developers.",
        "sentiment": "positive",
    },
    "freight": {
        "label": "Freight",
        "move": "+2.1%",
        "impact": "Higher freight can help logistics operators but weighs on import-heavy consumers.",
        "sentiment": "mixed",
    },
    "trade": {
        "label": "Trade",
        "move": "Regional flows firm",
        "impact": "Stronger trade flows support ports, logistics, warehousing, and free-zone activity.",
        "sentiment": "positive",
    },
    "tourism": {
        "label": "Tourism",
        "move": "Strong arrivals",
        "impact": "Tourism momentum supports aviation, real estate, malls, and toll traffic.",
        "sentiment": "positive",
    },
    "population-growth": {
        "label": "Population",
        "move": "Expanding",
        "impact": "Population growth supports utilities, tolls, housing, and consumption.",
        "sentiment": "positive",
    },
    "food-inputs": {
        "label": "Food Inputs",
        "move": "+1.4%",
        "impact": "Input-cost inflation can compress food and restaurant margins.",
        "sentiment": "cautious",
    },
    "power-demand": {
        "label": "Power Demand",
        "move": "Summer load rising",
        "impact": "Higher demand supports utility throughput and capacity planning.",
        "sentiment": "positive",
    },
    "desalination": {
        "label": "Desalination",
        "move": "Stable",
        "impact": "Water demand visibility supports regulated utility cash flows.",
        "sentiment": "positive",
    },
    "private-assets": {
        "label": "Private Assets",
        "move": "Valuation watch",
        "impact": "Private-asset marks need stronger disclosure evidence to build confidence.",
        "sentiment": "cautious",
    },
    "healthcare": {
        "label": "Healthcare",
        "move": "Demand resilient",
        "impact": "Healthcare demand is defensive, but acquisition integration matters.",
        "sentiment": "neutral",
    },
    "real-estate": {
        "label": "Real Estate",
        "move": "Dubai prices firm",
        "impact": "Real-estate momentum supports mortgage demand but raises affordability risk.",
        "sentiment": "mixed",
    },
    "sukuk": {
        "label": "Sukuk",
        "move": "Issuance active",
        "impact": "Active sukuk markets help Islamic bank funding and investor demand.",
        "sentiment": "positive",
    },
}
